In [1]:
import numpy as np
A = np.array([[1, 2, 3], [4, 2, 5], [7, 4, 9]]) #定义矩阵A
A #输出A

array([[1, 2, 3],
       [4, 2, 5],
       [7, 4, 9]])

In [2]:
A.shape #输出A的大小

(3, 3)

In [3]:
# X = np.array([[1, 2], [2, 3, 5],[6]]) 不均匀会报错
# X 输出x

In [4]:
A[1, 2] #下标是（1,2），同C++下标从0开始

np.int64(5)

In [5]:
A[0, :] #输出横坐标为0的行

array([1, 2, 3])

In [6]:
A[: ,1] #输出纵坐标为1的列

array([2, 2, 4])

In [7]:
A[:,0:2] #从纵坐标为0的列开始，往后输出两列

array([[1, 2],
       [4, 2],
       [7, 4]])

In [8]:
A[:,1:3]

array([[2, 3],
       [2, 5],
       [4, 9]])

In [9]:
A[0:2,1] #行从0开始往下找两行，列固定为下标1
#虽然在意义上输出的是列，但是在计算机上用行显示

array([2, 2])

In [10]:
B=A.T #B是A的转置矩阵
B #输出B

array([[1, 4, 7],
       [2, 2, 4],
       [3, 5, 9]])

In [11]:
print(A)
B
print(B[1, 2])
#如果不加print的话，默认只输出最后一行的变量（只写变量名）
# 想强制输出什么的话，就用print

[[1 2 3]
 [4 2 5]
 [7 4 9]]
4


In [12]:
A+B #矩阵A+矩阵B的和

array([[ 2,  6, 10],
       [ 6,  4,  9],
       [10,  9, 18]])

In [13]:
D = np.linalg.inv(A) #输出A的逆矩阵
D

array([[-1. , -3. ,  2. ],
       [-0.5, -6. ,  3.5],
       [ 1. ,  5. , -3. ]])

In [14]:
A@D #矩阵A和D的积

array([[ 1.00000000e+00,  0.00000000e+00, -4.44089210e-16],
       [ 1.11022302e-16,  1.00000000e+00,  4.44089210e-16],
       [-3.33066907e-16, -3.55271368e-15,  1.00000000e+00]])

In [15]:
np.dot(A,D) #矩阵A和D的积

array([[ 1.00000000e+00,  0.00000000e+00, -4.44089210e-16],
       [ 1.11022302e-16,  1.00000000e+00,  4.44089210e-16],
       [-3.33066907e-16, -3.55271368e-15,  1.00000000e+00]])

In [16]:
A*D # A和D的对应位置相乘
# 比如A的（1,1）位置的数和D（1,1）位置的数相乘就是答案的（1,1）位置的数

array([[ -1. ,  -6. ,   6. ],
       [ -2. , -12. ,  17.5],
       [  7. ,  20. , -27. ]])

In [17]:
np.linalg.eig(A) #A的固有值和对应的固有向量

EigResult(eigenvalues=array([13.49321177, -1.38629149, -0.10692028]), eigenvectors=array([[-0.27634299, -0.83217759, -0.39341216],
       [-0.46264258,  0.35902292, -0.69132945],
       [-0.84237545,  0.42259082,  0.60604493]]))